### ISSUE TITLE
[Crash 1.19.2] Crash when placing a Crate from the mod "@AppleCrates" close to a Wireless Charger.

### ISSUE THREAD

**Issue by Gbergz** [SuperMartijn642/WirelessChargers#13]
**Version Info**
- Minecraft, 1.19.2
- Wireless Chargers, [1.0.6b](https://www.curseforge.com/minecraft/mc-mods/wireless-chargers/files/3871937)

**Steps to Reproduce**
Place a wireless charger-
then place an apple crate beside it or in the range of it.
crash.

**Crash report (~/logs/latest.log)**
https://gist.github.com/Gbergz/ae68eaa30f6a4ba13ed0815cd79e2d2b

**Comment by SuperMartijn642** [comment]
This is caused by Apple Crates returning an `IItemHandler` when asked for an energy capability. This will likely cause issues with many mods and Apple Crates will have to fix it.

I would create a pull request to fix it in Apple Crates, but they haven't pushed the changes from their latest version to their GitHub repository 🤔.
So nothing I can do about this, you'll just have to report it to Apple Crates.

**Comment by AbsolemJackdaw** [comment]
> This is caused by Apple Crates returning an `IItemHandler` when asked for an energy capability. This will likely cause issues with many mods and Apple Crates will have to fix it.
> 
> I would create a pull request to fix it in Apple Crates, but they haven't pushed the changes from their latest version to their GitHub repository 🤔. So nothing I can do about this, you'll just have to report it to Apple Crates.

https://github.com/AbsolemJackdaw/AppleCrates/tree/hopper_support

It's there, just not in the main
I'm on it btw

**Comment by SuperMartijn642** [comment]
Ah I see, I just selected 1.19.2 without looking at the other branches 🤦‍♂️
Thanks for the quick response!
