### ISSUE TITLE
[Feature] Infinite distance/cross-dimensional chargers

### ISSUE THREAD

**Issue by blockbreaker1361** [SuperMartijn642/WirelessChargers#3]
Would it be possible for you to make chargers with infinite distance in your current dimension or maybe even make one that can charge items across dimensions. Would be invaluable for things like jetpacks and the Mining Gadget which requires power.

**Comment by SuperMartijn642** [comment]
For block chargers, this would of course not work.
For player chargers, I assume you'd bind a charger to a specific player. My main concern is then that the charger would need to be chunk loaded. I fear that most players won't understand that and I will get a ton of issues about why the charger is not working.

**Comment by blockbreaker1361** [comment]
I'm not being mean, just brutally honest. All you need to do is put in the description that they need to chunk load the charger in order for it to work at long distances. Would it not also be smart to tell them not to put an issue in the tracker for this?

**Comment by SuperMartijn642** [comment]
> All you need to do is put in the description that they need to chunk load the charger in order for it to work at long distances.

From experience with my other mods, simply putting it on the mod's CurseForge page is not sufficient. Even if I put it on the mod's CurseForge page description and FAQ, in the GitHub readme, and in my Discord server's FAQ, I will still get issues and questions about it. It needs to be a clear indication in game when using the proposed charger.

> Would it not also be smart to tell them not to put an issue in the tracker for this?

Where would I tell them so?

#### Some of my thoughts:
The main feature of the new charger is that it charges a player's items if the player is not close to the charger. This feature will only work if there's another mod which provides chunk loading. Thus, to use the new charger you would have to add another mod, which I don't like.
If I would add the new charger, I would like an in game indication as to it needing to be chunk loaded. For average players it will just feel buggy when the charger seemingly randomly stops working due to the chunk being unloaded. The indication could be given in the tooltip for the item or a status message to the player when the charger gets unloaded.
I would also like to clearly separate it from the current player chargers. I would likely do this through giving it a different name such as 'Personal Wireless Charger' and a separate recipe instead of an upgrade recipe like the advanced player charger has.

**Comment by willtarax** [comment]
Could you make the charger itself a block that chunkloads? That's what flux networks did with theirs

**Comment by rtr468** [comment]
Maybe Im a bit jaded, but it seems that most people understand chunk loading at this point, and FTBTeams does an OK job at loading chunks around peoples bases, while being in basically every major pack. Every version of a wireless power source has always had the loading limitation, and hasn't been that big of a deal for many folks. Kinda like Ender Chests or Ender Tanks, the idea has been here for a while, we kinda get it I believe. Your call ofc if you want it to be in your mod, balance or design or otherwise, all yours. Just something many people (including me) like to see in our wireless chargers! (also bc for some reason 1.18 seems to be lacking many of our previous favorites for that exact task cough cough)

**Comment by blockbreaker1361** [comment]
We have other mods to charge infinite distance now anyway such as FluxNetworks and Powah for 1.18.2. Let's just close this and be done with it.
