### ISSUE TITLE
[Feature] Add russian translation

### ISSUE THREAD

**Issue by Den4enko** [SuperMartijn642/WirelessChargers#4]
I translated this mod to russian language.
Please add this to mod
[ru_ru.zip](https://github.com/SuperMartijn642/WirelessChargers/files/8148406/ru_ru.zip)

**Comment by SuperMartijn642** [comment]
Again, thank you for the translations!

Could you submit the translations as a pull request? That way I can easily merge it and you will be credited with the changes.

To create a pull request:
Go to the assets folder and click 'Add file' -> 'Create new file'.
https://github.com/SuperMartijn642/WirelessChargers/tree/1.18/src/main/resources/assets/wirelesschargers
![image](https://user-images.githubusercontent.com/12382965/155899844-f313aeaa-8e7f-43bd-8d0c-88a8392e9cfb.png)
As file name you'll want to type 'lang/ru_ru.json'. The 'lang/' is there because the 'lang' folder doesn't exist yet.
![image](https://user-images.githubusercontent.com/12382965/155899926-e634cb34-99b9-426b-a70f-bf1dbca609a7.png)
Then add your translations into the file and press the 'Commit new file' button.
![image](https://user-images.githubusercontent.com/12382965/155899952-c48b7231-8fab-4823-9bbc-ed31f1c21d1b.png)
Let me know if you have any questions.

**Comment by Den4enko** [comment]
Thank you!
